language: r
sudo: false
cache: packages

dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:cran/v8'
    packages:
      - libnode-dev

r_github_packages:
  - r-lib/pkgdepends

matrix:
  include:
   - r: 3.2
   - r: 3.3
   - r: 3.4
   - r: 3.5
   - r: release
     before_cache:
       - Rscript -e 'install.packages("remotes")'
       - Rscript -e 'remotes::install_cran("pkgdown")'
       - Rscript -e 'remotes::install_github("r-lib/asciicast")'
     deploy:
       provider: script
       script: Rscript -e 'pkgdown::deploy_site_github()'
       skip_cleanup: true
       on:
         all_branches: true
         condition: $TRAVIS_BRANCH =~ ^(master|feature/pkgdown)$
     dist: xenial
     addons:
       apt:
         packages: libnode-dev
   - r: devel

r:
 - 3.2
 - 3.3
 - 3.4
 - oldrel
 - release
 - devel

matrix:
  allow_failures:
    - r: 3.2

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

env:
  global:
  - NOT_CRAN="true"
  - _R_CHECK_SYSTEM_CLOCK_="FALSE"
