language: r
sudo: false
cache: packages

r_github_packages:
  - r-lib/pkgdepends
r:
 - 3.2
 - 3.3
 - 3.4
 - oldrel
 - release
 - devel

matrix:
  allow_failures:
    - r: 3.2

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

env:
  global:
  - NOT_CRAN="true"
  - _R_CHECK_SYSTEM_CLOCK_="FALSE"
